### ISSUE TITLE
MYOCYTER bug ImageJ 1.53

### ISSUE THREAD

**Issue by kevindrbio** [Myocyter/Myocyter-v1.3#1]
Dear Dr. Jung,

I recently found your software and am planning to utilize it to analyze iPSC derived cardiomyocyte beating. I downloaded the most recent version of ImageJ from the NIH website and was unable to reproduce your analysis of the "two cardiomyocytes.avi" file using the settings from the manual. I was able to find version 1.52 from the imageJ repository which led to an error free run.

The errors I experienced were during analysis in which the macro ended with the error:
`No windows with the title "Result of two cardiomyocytes-2.avi" found`

I was able to reproduce the error on two separate computers with ImageJ 5.3 but have had success with ImageJ 5.2

Regards,
Kevin

**Comment by Myocyter** [comment]
Dear Kevin,
I am sorry about this. This problem results from a changed naming of copied files from "filename-1" to "filename-1-1" instead of "filename-2". This has already been changed back and forth several times with updates and adjusting the macro can still cause malfunctions after the next update. Thus, I uploaded a link to a functional version of ImageJ (version 1.52a) here in GitHub:

https://drive.google.com/file/d/1wY5P4SsfjAx0cRfVubYFPOvcrwBbhZ7p/view?usp=sharing

Dear user(s), if there are any problems with "Myocyter", please contact me:

tobias.jung@dife.de

**Comment by kevindrbio** [comment]
Thank you for making the optimized version available and thank you for contributing this software. We are looking forward to using it!
